
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/database_c'
    username: 'nikent'
    password: 'qq5QTTyd6fOiHpSdJdm9mRbVtLs22T0n'
#    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

#    tomcat:
#      max-wait: 10000
#      max-active: 50
#      test-on-borrow: true
