
spring:
  application:
    name: config-client
  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:8888

#  cloud:
#    config:
#      label: spring-cloud-config

vars:
  variable_one:
    value: inside-config-client
