
server:
  port: '8080'

## With Config Server we can get rid of this repetition

rabbitmq:
  exchanges:
    order-direct: 'order-direct-exchange'
  queues:
    payment: 'payment-queue'
    inventory: 'inventory-queue'
    shipping: 'shipping-queue'
  routing-keys:
    payment: 'payment'
    inventory: 'inventory'
    shipping: 'shipping'

spring:
  rabbitmq:
    virtual-host: 'ovihavzd'
    host: 'sparrow.rmq.cloudamqp.com'
    port: '5672'
    username: 'ovihavzd'
    password: 'dEzfxr-2Cqwh1g8KxPRMt36uftJPss4B'
#    url: 'amqps://ovihavzd:dEzfxr-2Cqwh1g8KxPRMt36uftJPss4B@sparrow.rmq.cloudamqp.com/ovihavzd'
